export const DRIVER_ROSTER_REVIEWED_AT = "2026-08-14";

export const CURRENT_DRIVER_GALLERY_SOURCE = {
  url: "https://nascar25.com/drivers/",
  publishedAt: "2025-10-02",
  modifiedAt: "2025-10-10",
} as const;

export const DRIVER_ROSTER_SOURCES = {
  CUP: {
    label: "Cup Series",
    url: "https://nascar25.com/nascar-25-driver-roster-cup-series/",
    publishedAt: "2025-08-05",
  },
  XFI: {
    label: "Xfinity Series",
    url: "https://nascar25.com/nascar-25-driver-roster-xfinity-series/",
    publishedAt: "2025-08-01",
  },
  TRK: {
    label: "Craftsman Truck Series",
    url: "https://nascar25.com/nascar-25-driver-roster-craftsman-truck-series/",
    publishedAt: "2025-07-30",
  },
  ARCA: {
    label: "ARCA Menards Series",
    url: "https://nascar25.com/nascar-25-driver-roster-arca-menards-series/",
    publishedAt: "2025-07-28",
  },
} as const;

export type DriverSeriesCode = keyof typeof DRIVER_ROSTER_SOURCES;
type DriverTuple = readonly [carNumber: string, name: string, team: string];

const OFFICIAL_ROSTERS: Record<DriverSeriesCode, readonly DriverTuple[]> = {
  CUP: [
    ["01", "Corey LaJoie", "Rick Ware Racing"],
    ["1", "Ross Chastain", "Trackhouse Racing"],
    ["2", "Austin Cindric", "Team Penske"],
    ["3", "Austin Dillon", "Richard Childress Racing"],
    ["4", "Noah Gragson", "Front Row Motorsports"],
    ["5", "Kyle Larson", "Hendrick Motorsports"],
    ["6", "Brad Keselowski", "RFK Racing"],
    ["7", "Justin Haley", "Spire Motorsports"],
    ["8", "Kyle Busch", "Richard Childress Racing"],
    ["9", "Chase Elliott", "Hendrick Motorsports"],
    ["10", "Ty Dillon", "Kaulig Racing"],
    ["11", "Denny Hamlin", "Joe Gibbs Racing"],
    ["12", "Ryan Blaney", "Team Penske"],
    ["16", "AJ Allmendinger", "Kaulig Racing"],
    ["17", "Chris Buescher", "RFK Racing"],
    ["19", "Chase Briscoe", "Joe Gibbs Racing"],
    ["20", "Christopher Bell", "Joe Gibbs Racing"],
    ["21", "Josh Berry", "Wood Brothers Racing"],
    ["22", "Joey Logano", "Team Penske"],
    ["23", "Bubba Wallace", "23XI Racing"],
    ["24", "William Byron", "Hendrick Motorsports"],
    ["34", "Todd Gilliland", "Front Row Motorsports"],
    ["35", "Riley Herbst", "23XI Racing"],
    ["38", "Zane Smith", "Front Row Motorsports"],
    ["40", "Justin Allgaier", "JR Motorsports"],
    ["41", "Cole Custer", "Haas Factory Team"],
    ["42", "John Hunter Nemechek", "Legacy Motor Club"],
    ["43", "Erik Jones", "Legacy Motor Club"],
    ["44", "JJ Yeley", "NY Racing"],
    ["45", "Tyler Reddick", "23XI Racing"],
    ["47", "Ricky Stenhouse Jr.", "Hyak Motorsports"],
    ["48", "Alex Bowman", "Hendrick Motorsports"],
    ["50", "Burt Myers", "Team Amerivet"],
    ["51", "Cody Ware", "Rick Ware Racing"],
    ["54", "Ty Gibbs", "Joe Gibbs Racing"],
    ["56", "Martin Truex Jr.", "Tricon Garage"],
    ["60", "Ryan Preece", "RFK Racing"],
    ["66", "Chad Finchum", "MBM Motorsports"],
    ["66", "Josh Bilicki", "MBM Motorsports"],
    ["71", "Michael McDowell", "Spire Motorsports"],
    ["77", "Carson Hocevar", "Spire Motorsports"],
    ["78", "BJ McLeod", "Live Fast Motorsports"],
    ["84", "Jimmie Johnson", "Legacy Motor Club"],
    ["87", "Connor Zilisch", "Trackhouse Racing"],
    ["88", "Shane Van Gisbergen", "Trackhouse Racing"],
    ["91", "Helio Castroneves", "Trackhouse Racing"],
    ["99", "Daniel Suarez", "Trackhouse Racing"],
  ],
  XFI: [
    ["00", "Sheldon Creed", "Haas Factory Team"],
    ["1", "Carson Kvapil", "JR Motorsports"],
    ["2", "Jesse Love", "Richard Childress Racing"],
    ["4", "Parker Retzlaff", "Alpha Prime Racing"],
    ["07", "Patrick Emerling", "SS-Greenlight Racing"],
    ["07", "Nick Leitz", "SS-Greenlight Racing"],
    ["7", "Justin Allgaier", "JR Motorsports"],
    ["8", "Sammy Smith", "JR Motorsports"],
    ["9", "Daniel Suarez", "JR Motorsports"],
    ["9", "Ross Chastain", "JR Motorsports"],
    ["9", "Shane Van Gisbergen", "JR Motorsports"],
    ["10", "Daniel Dye", "Kaulig Racing"],
    ["11", "Josh Williams", "Kaulig Racing"],
    ["14", "Garrett Smithley", "SS-Greenlight Racing"],
    ["16", "Christian Eckes", "Kaulig Racing"],
    ["17", "Corey Day", "Hendrick Motorsports"],
    ["18", "William Sawalich", "Joe Gibbs Racing"],
    ["19", "Aric Almirola", "Joe Gibbs Racing"],
    ["20", "Brandon Jones", "Joe Gibbs Racing"],
    ["21", "Austin Hill", "Richard Childress Racing"],
    ["24", "Ryan Truex", "Sam Hunt Racing"],
    ["25", "Harrison Burton", "AM Racing"],
    ["26", "Dean Thompson", "Sam Hunt Racing"],
    ["27", "Jeb Burton", "Jordan Anderson Racing"],
    ["28", "Kyle Sieg", "RSS Racing"],
    ["31", "Blaine Perkins", "Jordan Anderson Racing"],
    ["32", "Jordan Anderson", "Jordan Anderson Racing"],
    ["35", "Greg Van Alst", "Joey Gase Racing"],
    ["39", "Ryan Sieg", "RSS Racing"],
    ["41", "Sam Mayer", "Haas Factory Team"],
    ["42", "Anthony Alfredo", "Young’s Motorsports"],
    ["44", "Brennan Poole", "Alpha Prime Racing"],
    ["45", "Mason Massey", "Alpha Prime Racing"],
    ["45", "Brad Perez", "Alpha Prime Racing"],
    ["45", "Caesar Bacarella", "Alpha Prime Racing"],
    ["48", "Nick Sanchez", "Big Machine Racing"],
    ["50", "Preston Pardus", "Pardus Racing"],
    ["51", "Jeremy Clements", "Jeremy Clements Racing"],
    ["53", "Joey Gase", "Joey Gase Racing"],
    ["54", "Taylor Gray", "Joe Gibbs Racing"],
    ["66", "Chad Finchum", "MBM Motorsports"],
    ["70", "Leland Honeyman Jr.", "Cope Family Racing"],
    ["70", "Thomas Annunziata", "Cope Family Racing"],
    ["71", "Ryan Ellis", "DGM Racing"],
    ["74", "Dawson Cram", "Mike Harmon Racing"],
    ["87", "Austin Green", "Jordan Anderson Racing"],
    ["88", "Connor Zilisch", "JR Motorsports"],
    ["91", "Josh Bilicki", "DGM Racing"],
    ["91", "Jesse Iwuji", "DGM Racing × Jesse Iwuji Motorsports"],
    ["99", "Matt DiBenedetto", "Viking Motorsports"],
  ],
  TRK: [
    ["1", "Brandon Jones", "Tricon Garage"],
    ["1", "Brent Crews", "Tricon Garage"],
    ["1", "Lawless Alan", "Tricon Garage"],
    ["1", "William Sawalich", "Tricon Garage"],
    ["2", "Cody Dennison", "Reaume Brothers Racing"],
    ["04", "Cory Roper", "Roper Racing"],
    ["5", "Toni Breidinger", "Tricon Garage"],
    ["6", "Norm Benning", "Norm Benning Racing"],
    ["07", "Corey LaJoie", "Spire Motorsports"],
    ["07", "Kyle Larson", "Spire Motorsports"],
    ["7", "Kyle Busch", "Spire Motorsports"],
    ["9", "Grant Enfinger", "CR7 Motorsports"],
    ["11", "Corey Heim", "Tricon Garage"],
    ["13", "Jake Garcia", "ThorSport Racing"],
    ["15", "Tanner Gray", "Tricon Garage"],
    ["17", "Gio Ruggiero", "Tricon Garage"],
    ["18", "Tyler Ankrum", "McAnally-Hilgemann Racing"],
    ["19", "Daniel Hemric", "McAnally-Hilgemann Racing"],
    ["21", "Jayson Alexander", "Floridian Motorsports"],
    ["22", "Josh Reaume", "Reaume Brothers Racing"],
    ["23", "Stephen Mallozzi", "Reaume Brothers Racing"],
    ["26", "Dawson Sutton", "Rackley W.A.R."],
    ["28", "Bryan Dauzat", "FDNY Racing"],
    ["33", "Frankie Muniz", "Reaume Brothers Racing"],
    ["34", "Layne Riggs", "Front Row Motorsports"],
    ["38", "Chandler Smith", "Front Row Motorsports"],
    ["42", "Matt Mills", "Niece Motorsports"],
    ["44", "Bayley Currey", "Niece Motorsports"],
    ["44", "Conner Jones", "Niece Motorsports"],
    ["44", "Josh Bilicki", "Niece Motorsports"],
    ["44", "Matt Gould", "Niece Motorsports"],
    ["44", "Ross Chastain", "Niece Motorsports"],
    ["45", "Kaden Honeycutt", "Niece Motorsports"],
    ["52", "Stewart Friesen", "Halmar Friesen Racing"],
    ["56", "Timmy Hill", "Hill Motorsports"],
    ["66", "Johnny Sauter", "ThorSport Racing"],
    ["66", "Luke Baldwin", "ThorSport Racing"],
    ["66", "Luke Fenhaus", "ThorSport Racing"],
    ["71", "Rajah Caruth", "Spire Motorsports"],
    ["74", "Caleb Costner", "Mike Harmon Racing"],
    ["75", "Parker Kligerman", "Henderson Motorsports"],
    ["76", "Spencer Boyd", "Freedom Racing Enterprises"],
    ["77", "Andres Perez de Lara", "Spire Motorsports"],
    ["81", "Connor Mosack", "McAnally-Hilgemann Racing"],
    ["88", "Matt Crafton", "ThorSport Racing"],
    ["91", "Jack Wood", "McAnally-Hilgemann Racing"],
    ["95", "Clay Greenfield", "GK Racing"],
    ["98", "Ty Majeski", "ThorSport Racing"],
    ["99", "Ben Rhodes", "ThorSport Racing"],
  ],
  ARCA: [
    ["0", "Nate Moeller", "Wayne Peterson Racing"],
    ["01", "EJ Tamayo", "Fast Track Racing"],
    ["2", "Eloy Falcon", "Rev Racing"],
    ["2", "Lanie Buice", "Rev Racing"],
    ["03", "Alex Clubb", "Clubb Racing Inc."],
    ["3", "Alex Quarterley", "1/4 Ley Racing"],
    ["3", "Todd Souza", "Central Coast Racing"],
    ["3", "Willie Mullins", "Mullins Racing"],
    ["4", "Dale Quarterley", "1/4 Ley Racing"],
    ["05", "David Smith", "Shockwave Motorsports"],
    ["5", "Eric Johnson Jr.", "Jerry Pitts Racing"],
    ["06", "Brayton Laster", "Wayne Peterson Racing"],
    ["6", "Lavar Scott", "Rev Racing"],
    ["8", "Sean Corr", "Empire Motorsports"],
    ["9", "Cody Dennison", "Fast Track Racing"],
    ["9", "Robbie Kennealy", "Jan’s Racing (KKM)"],
    ["10", "Ed Pompa", "Fast Track Racing"],
    ["11", "Zachary Tinkle", "Fast Track Racing"],
    ["12", "Takuma Koga", "Fast Track Racing"],
    ["13", "Tanner Reif", "Central Coast Racing"],
    ["15", "Patrick Staropoli", "Venturini Motorsports"],
    ["18", "William Sawalich", "Joe Gibbs Racing"],
    ["19", "Jake Bollman", "Bill McAnally Racing"],
    ["20", "Lawless Alan", "Venturini Motorsports"],
    ["22", "Amber Balcaen", "Venturini Motorsports"],
    ["23", "Tyler Reif", "Sigma Performance"],
    ["25", "Jake Finch", "Venturini Motorsports"],
    ["27", "Tim Richmond", "Tim Richmond Racing"],
    ["28", "Brenden Queen", "Pinnacle Racing Group"],
    ["29", "Kyle Steckly", "Rette Jones Racing"],
    ["30", "Cleetus McFarland", "Rette Jones Racing"],
    ["31", "Rita Goulet", "Rise Motorsports"],
    ["35", "Greg Van Alst", "Greg Van Alst Motorsports"],
    ["39", "D.L. Wilson", "CW Motorsports"],
    ["46", "Thad Moffitt", "Nitro Motorsports"],
    ["48", "Brad Smith", "Brad Smith Motorsports"],
    ["50", "Trevor Huddleston", "High Point Motorsports"],
    ["51", "Blake Lothian", "Strike Mamba Racing"],
    ["55", "Isabella Robusto", "Venturini Motorsports"],
    ["56", "Timmy Hill", "Hill Motorsports"],
    ["62", "Steve Lewis Jr.", "Steve Lewis Racing"],
    ["66", "Presley Sorah", "Maples Motorsports"],
    ["67", "Ryan Roulette", "Maples Motorsports"],
    ["69", "Will Kimmel", "Kimmel Racing"],
    ["71", "Kyle Keller", "Jan’s Racing"],
    ["72", "Jonathan Reaume", "Strike Mamba Racing"],
    ["73", "Andy Jankowiak", "Klas Motorsports"],
    ["76", "Kole Raz", "AM Racing"],
    ["77", "Corey Day", "Spire Motorsports"],
    ["79", "Isaac Kitzmiller", "CR7 Motorsports"],
    ["85", "Becca Monopoli", "City Garage Motorsports"],
    ["86", "Brian Clubb", "Clubb Racing Inc."],
    ["88", "A.J. Moyer", "Moyer Petroniro Racing"],
    ["93", "Caleb Costner", "CW Motorsports"],
    ["95", "Hunter Wright", "Man Motorsports"],
    ["96", "Jackson McLerran", "Man Motorsports"],
    ["97", "Jason Kitzmiller", "CR7 Motorsports"],
    ["99", "Michael Maples", "Maples Motorsports"],
  ],
};

export type DriverSeed = {
  seriesCode: DriverSeriesCode;
  carNumber: string;
  name: string;
  team: string;
  inGameRating: null;
  sourceUrl: string;
  publishedAt: string;
  reviewedAt: string;
};

export const DRIVER_SEED: DriverSeed[] = (
  Object.keys(DRIVER_ROSTER_SOURCES) as DriverSeriesCode[]
).flatMap((seriesCode) =>
  OFFICIAL_ROSTERS[seriesCode].map(([carNumber, name, team]) => ({
    seriesCode,
    carNumber,
    name,
    team,
    inGameRating: null,
    sourceUrl: CURRENT_DRIVER_GALLERY_SOURCE.url,
    publishedAt: CURRENT_DRIVER_GALLERY_SOURCE.modifiedAt,
    reviewedAt: DRIVER_ROSTER_REVIEWED_AT,
  })),
);
